on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '19' ]
        distribution: [ 'temurin' ]
        include:
          - java: '7'
            distribution: 'zulu'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - run: mvn --version
      - run: mvn package --errors --batch-mode
  java6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: '3.2.5'
      - uses: actions/setup-java@v3
        with:
          java-version: '6'
          distribution: 'zulu'
      - run: mvn --version
      - run: mvn package --errors --batch-mode --settings .github/workflows/nossl.settings.xml
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: mvn --version
      - run: mvn package --errors --batch-mode -P release
